version: '3'
services:
  zammad-gateway:
    build: .
    ports:
      - 8081:8081
    environment:
      - ZAMMAD_URL_DOCKER=${ZAMMAD_URL_ENV}
      - ZAMMAD_API_KEY_DOCKER=${ZAMMAD_API_KEY_ENV}
      - MAGENTO_URL_DOCKER=${MAGENTO_URL_ENV}
      - ORGANIZATION_NAME_DOCKER=${ORGANIZATION_NAME_ENV}
      - CHATBOT_SECURITY_KEY_DOCKER=${CHATBOT_SECURITY_KEY_ENV}
    volumes:
      - ./src:/app
    restart: unless-stopped